
const results_cat = {
    "ISTJ": { title: "규칙 냥이", desc: "정해진 시간에 츄르를 먹어야 해요.", interpretation: "책임감이 강하고 질서를 중요시하는 신뢰의 아이콘입니다.", guide: "규칙을 중시하는 아이입니다.", mood: "cool", color: "bg-blue-100" },
    "ISFJ": { title: "천사 냥이", desc: "집사가 힘들면 옆에서 골골송을 불러줘요.", interpretation: "타인의 감정을 읽고 헌신적으로 돌보는 따뜻한 마음의 소유자입니다.", guide: "집사가 힘들 때 먼저 다가오는 공감 능력이 뛰어납니다.", mood: "happy", color: "bg-pink-100" },
    "INFJ": { title: "철학 냥이", desc: "창밖을 보며 우주의 섭리를 생각해요.", interpretation: "깊은 통찰력과 이상주의를 가진 예언자적인 성격입니다.", guide: "혼자만의 사색 시간을 존중해 주세요.", mood: "sad", color: "bg-purple-100" },
    "INTJ": { title: "보스 냥이", desc: "집 정복 계획을 세우고 있어요.", interpretation: "독립적이고 전략적인 마스터마인드입니다.", guide: "똑똑해서 복종을 강요하기보다 '제안'하는 것이 효과적입니다.", mood: "cool", color: "bg-indigo-100" },
    "ISTP": { title: "만능 냥이", desc: "혼자서도 장난감을 잘 고치고 놀아요.", interpretation: "호기심 많고 뛰어난 문제 해결 능력자입니다.", guide: "혼자 탐색하고 놀 수 있는 다양한 도구를 제공해 주세요.", mood: "cool", color: "bg-gray-100" },
    "ISFP": { title: "예술 냥이", desc: "벽지에 멋진 스크래치 아트를 남겨요.", interpretation: "현재를 즐기며 아름다움을 추구하는 자유로운 영혼입니다.", guide: "오감을 만족시킬 수 있는 환경을 만들어 주세요.", mood: "excited", color: "bg-yellow-100" },
    "INFP": { title: "몽상 냥이", desc: "나비 쫓아가다 길을 잃을 뻔 했어요.", interpretation: "깊은 감정과 가치를 중시하는 이상주의자입니다.", guide: "따뜻한 격려가 필요합니다.", mood: "sad", color: "bg-green-100" },
    "INTP": { title: "박사 냥이", desc: "장난감의 원리를 분석하고 있어요.", interpretation: "지적 호기심이 왕성하고 논리적인 천재입니다.", guide: "다양한 방식으로 숨겨진 간식을 찾는 놀이를 제공해 주세요.", mood: "cool", color: "bg-blue-100" },
    "ESTP": { title: "액션 냥이", desc: "캣타워 꼭대기에서 점프하는 걸 좋아해요!", interpretation: "타고난 모험가이자 현장형 해결사입니다.", guide: "충분한 사냥 놀이 시간을 확보해 주세요.", mood: "excited", color: "bg-red-100" },
    "ESFP": { title: "인싸 냥이", desc: "새로운 고양이를 만나면 먼저 다가가요.", interpretation: "분위기 메이커이자 활발한 활동가입니다.", guide: "집사의 적극적인 반응과 관심이 필요합니다.", mood: "happy", color: "bg-orange-100" },
    "ENFP": { title: "댕댕 냥이", desc: "고양이지만 강아지처럼 사람을 좋아해요!", interpretation: "열정적이고 창의적인 사교적 혁신가입니다.", guide: "정서적인 유대감을 매우 중요하게 생각합니다.", mood: "excited", color: "bg-yellow-100" },
    "ENTP": { title: "장난 냥이", desc: "집사가 하지 말라는 것만 골라서 해요.", interpretation: "똑똑하고 논리적인 토론가입니다.", guide: "호기심을 충족시킬 수 있는 '안전한' 도전 과제를 만들어 주세요.", mood: "cool", color: "bg-red-100" },
    "ESTJ": { title: "대장 냥이", desc: "동네 고양이들을 관리 감독해요.", interpretation: "체계적이고 현실적인 리더입니다.", guide: "서열을 인정받고 싶어 합니다.", mood: "cool", color: "bg-blue-200" },
    "ESFJ": { title: "마미 냥이", desc: "동네 냥이들 밥을 다 챙겨줘요.", interpretation: "따뜻하고 사려 깊은 조력자입니다.", guide: "집사의 기분을 살피고 맞춰주려 노력합니다.", mood: "happy", color: "bg-pink-200" },
    "ENFJ": { title: "아이돌 냥이", desc: "모두에게 사랑받는 인기쟁이!", interpretation: "카리스마 있고 영감을 주는 지도자입니다.", guide: "충분한 칭찬과 사랑을 표현해 주어야 행복합니다.", mood: "happy", color: "bg-purple-200" },
    "ENTJ": { title: "회장 냥이", desc: "이 구역의 츄르는 다 내꺼야.", interpretation: "결단력 있고 야심 찬 전략가입니다.", guide: "자신의 영역을 확실히 확보해 주어야 합니다.", mood: "cool", color: "bg-indigo-200" }
};

const results_dog = {
    "ISTJ": { title: "규율 멍멍이", desc: "산책 시간이 되면 30분 전부터 현관 앞에서 기다린다.", interpretation: "성실하고 책임감이 강합니다.", guide: "명확하고 일관된 규칙이 필요합니다.", mood: "cool", color: "bg-blue-200" },
    "ISFJ": { title: "헌신 멍멍이", desc: "보호자가 아프면 옆에서 떨어지지 않고 간호한다.", interpretation: "정이 많고 헌신적입니다.", guide: "항상 차분하고 따뜻한 태도를 유지해 주세요.", mood: "happy", color: "bg-pink-200" },
    "INFJ": { title: "선구자 멍멍이", desc: "가족들의 마음을 읽고 먼저 행동하는 예언가", interpretation: "깊은 통찰력으로 가족의 필요를 미리 예측합니다.", guide: "지루함을 쉽게 느끼니 정신적 자극을 주세요.", mood: "sad", color: "bg-purple-100" },
    "INTJ": { title: "전략가 멍멍이", desc: "가족 구성원들의 약점을 파악하고 간식을 쟁취한다.", interpretation: "독립적이고 분석적입니다.", guide: "스스로 생각할 시간을 존중해 주세요.", mood: "cool", color: "bg-indigo-100" },
    "ISTP": { title: "탐험가 멍멍이", desc: "새로운 냄새가 나면 절대 놓치지 않고 따라간다.", interpretation: "호기심이 많고 즉흥적입니다.", guide: "충분한 노즈 워크와 탐색 시간을 제공해 주세요.", mood: "cool", color: "bg-gray-100" },
    "ISFP": { title: "감성 멍멍이", desc: "아름다운 잔디밭에 누워 햇살을 즐기는 힐링 전문가", interpretation: "현재의 감각을 중요시합니다.", guide: "조용하고 부드러운 환경을 유지해 주세요.", mood: "happy", color: "bg-yellow-100" },
    "INFP": { title: "시인 멍멍이", desc: "깊은 감성을 가진 사랑스러운 몽상가", interpretation: "깊은 감정과 가치를 중시합니다.", guide: "꾸준한 애정 표현으로 안심시켜 주세요.", mood: "sad", color: "bg-green-100" },
    "INTP": { title: "지식인 멍멍이", desc: "장난감의 원리를 분석하고 가장 효율적인 방법으로 파괴한다.", interpretation: "지적 호기심이 왕성합니다.", guide: "두뇌를 사용하는 복잡한 훈련이 필요합니다.", mood: "cool", color: "bg-blue-100" },
    "ESTP": { title: "활동가 멍멍이", desc: "공원 전체가 내 무대! 지치지 않는 에너자이저", interpretation: "에너지 넘치고 활동적입니다.", guide: "충분한 운동과 야외 활동이 필수입니다.", mood: "excited", color: "bg-red-100" },
    "ESFP": { title: "스타 멍멍이", desc: "지나가는 모든 사람에게 꼬리 흔드는 인기쟁이", interpretation: "사교적이고 낙천적입니다.", guide: "사람들과 어울릴 수 있는 기회를 많이 만들어 주세요.", mood: "happy", color: "bg-orange-100" },
    "ENFP": { title: "해피 멍멍이", desc: "세상은 즐거운 일로 가득해! 호기심 대장", interpretation: "열정적이고 상상력이 풍부합니다.", guide: "다양한 놀이와 경험을 제공해 주세요.", mood: "excited", color: "bg-yellow-100" },
    "ENTP": { title: "천재 멍멍이", desc: "잠긴 문도 여는 탈출의 귀재", interpretation: "영리하고 독창적입니다.", guide: "지루하지 않게 새로운 장난감을 자주 바꿔주세요.", mood: "cool", color: "bg-red-100" },
    "ESTJ": { title: "반장 멍멍이", desc: "집안의 평화를 지키는 든든한 보디가드", interpretation: "책임감이 강하고 규칙적입니다.", guide: "역할을 부여하고 칭찬해 주면 좋아합니다.", mood: "cool", color: "bg-blue-200" },
    "ESFJ": { title: "천사 멍멍이", desc: "가족들이 웃으면 나도 좋아! 공감 요정", interpretation: "친절하고 협조적입니다.", guide: "가족과 함께하는 시간을 가장 좋아합니다.", mood: "happy", color: "bg-pink-200" },
    "ENFJ": { title: "리더 멍멍이", desc: "다른 강아지들을 이끄는 골목대장", interpretation: "카리스마 있고 사교적입니다.", guide: "적극적인 칭찬과 스킨십이 필요합니다.", mood: "happy", color: "bg-purple-200" },
    "ENTJ": { title: "CEO 멍멍이", desc: "내가 가자고 하는 길로 가야 직성이 풀린다.", interpretation: "주도적이고 결단력이 있습니다.", guide: "일관된 훈련과 리더십이 필요합니다.", mood: "cool", color: "bg-indigo-200" }
};

const appData = {
    human: {
        title: "인간 성격 테스트",
        themeColor: "bg-[#BDE0FE]",
        icon: "HumanIcon",
        questions: [
            { q: "오랜만에 동창회에 나갔다! 어색한 친구들 사이에서 나는?", type: "EI", a: [{ text: "먼저 말을 걸며 분위기를 띄운다.", score: "E" }, { text: "친한 친구 옆에 딱 붙어서 조용히 있는다.", score: "I" }] },
            { q: "주말에 아무 약속이 없다면?", type: "EI", a: [{ text: "심심해... 친구들에게 연락해 약속을 잡는다.", score: "E" }, { text: "나이스! 밀린 넷플릭스를 보며 침대와 한 몸이 된다.", score: "I" }] },
            { q: "갑자기 모르는 번호로 전화가 걸려온다면?", type: "EI", a: [{ text: "여보세요? 일단 받고 누구인지 확인한다.", score: "E" }, { text: "스팸인가? 고민하다가 끊어지면 안도한다.", score: "I" }] },
            { q: "멍 때릴 때 주로 하는 생각은?", type: "SN", a: [{ text: "오늘 저녁 뭐 먹지? 내일 할 일이 뭐더라?", score: "S" }, { text: "좀비 사태가 터지면 어디로 도망가지? 로또 당첨되면...", score: "N" }] },
            { q: "영화를 보고 나서 친구와 대화할 때 나는?", type: "SN", a: [{ text: "주인공이 입은 옷 예쁘더라. 액션씬 대박이었어.", score: "S" }, { text: "그 결말의 의미는 뭘까? 감독이 전하려는 메시지는...", score: "N" }] },
            { q: "요리 레시피를 볼 때 나는?", type: "SN", a: [{ text: "소금 1작은술... 계량스푼으로 정확히 맞춘다.", score: "S" }, { text: "이 정도면 되겠지? 감으로 대충 넣거나 내 맘대로 바꾼다.", score: "N" }] },
            { q: "친구가 '나 우울해서 빵 샀어'라고 했을 때 나의 반응은?", type: "TF", a: [{ text: "무슨 빵 샀어? 맛있어?", score: "T" }, { text: "무슨 일 있어? 왜 우울해 ㅠㅠ", score: "F" }] },
            { q: "친구가 머리를 자르고 왔는데, 솔직히 좀 별로다. 이때 나는?", type: "TF", a: [{ text: "음... 전이 더 나은 것 같은데? 솔직하게 말한다.", score: "T" }, { text: "오~ 변화를 줬네! 기분 전환 됐겠다! 돌려 말하거나 칭찬한다.", score: "F" }] },
            { q: "조별 과제 중, 열심히 했지만 결과물이 별로인 팀원에게 피드백한다면?", type: "TF", a: [{ text: "이 부분은 수정이 필요해요. 부족한 점을 명확히 짚어준다.", score: "T" }, { text: "고생 많으셨어요! 근데 이 부분만 조금 더... 격려부터 한다.", score: "F" }] },
            { q: "여행 가기 전날, 나의 짐 싸기 스타일은?", type: "JP", a: [{ text: "며칠 전부터 리스트를 작성하고 차곡차곡 싸둔다.", score: "J" }, { text: "출발 직전에 '지갑, 여권! 챙겼으면 됐지!' 하고 후다닥 싼다.", score: "P" }] },
            { q: "2주 뒤가 시험이다. 나의 공부 계획은?", type: "JP", a: [{ text: "일별로 공부할 분량을 나눠서 계획을 짠다.", score: "J" }, { text: "아직 2주나 남았네? 일단 놀다가 벼락치기한다.", score: "P" }] },
            { q: "친구와 맛집에 갔는데 문이 닫혀있다! 이때 나는?", type: "JP", a: [{ text: "아... 어떡하지? 미리 찾아둔 2순위 식당으로 간다.", score: "J" }, { text: "할 수 없지! 저기 맛있어 보이는데 갈까? 바로 옆 가게로 간다.", score: "P" }] },
        ],
        questions_deep: [
            { q: "일주일 동안 사람들을 만나지 않고 집에만 있었다면?", type: "EI", a: [{ text: "좀이 쑤신다. 세상과 단절된 느낌이 들어 우울하다.", score: "E" }, { text: "너무 평화롭다. 에너지가 완전히 충전된 기분이다.", score: "I" }] },
            { q: "대화 중 침묵이 흐르는 순간, 나는?", type: "EI", a: [{ text: "어색함을 견딜 수 없어 무슨 말이든 꺼내 분위기를 띄운다.", score: "E" }, { text: "침묵도 대화의 일부라고 생각하며 편안하게 기다린다.", score: "I" }] },
            { q: "나의 인간관계 스타일은?", type: "EI", a: [{ text: "넓고 얕은 관계. 다양한 사람들과 어울리는 것이 좋다.", score: "E" }, { text: "좁고 깊은 관계. 소수의 사람과 깊은 이야기를 나누는 것이 좋다.", score: "I" }] },
            { q: "파티나 모임에서 나는 주로?", type: "EI", a: [{ text: "무대 중앙이나 시끌벅적한 곳에서 에너지를 발산한다.", score: "E" }, { text: "구석진 자리나 조용한 곳에서 한두 명과 대화하거나 관찰한다.", score: "I" }] },
            { q: "고민이 생겼을 때 나는?", type: "EI", a: [{ text: "친구들에게 털어놓고 이야기하며 해결책을 찾는다.", score: "E" }, { text: "혼자 조용히 생각하며 스스로 답을 내릴 때까지 삭힌다.", score: "I" }] },
            { q: "새로운 모임에 나갔을 때 나의 자기소개 스타일은?", type: "EI", a: [{ text: "안녕하세요! 저는~ 먼저 나서서 활기차게 나를 알린다.", score: "E" }, { text: "사회자가 시키거나 순서가 되면 차분하게 짧게 이야기한다.", score: "I" }] },
            { q: "사과라는 단어를 들으면 떠오르는 것은?", type: "SN", a: [{ text: "빨갛다, 맛있다, 동그랗다, 아삭하다.", score: "S" }, { text: "백설공주, 뉴턴, 애플(아이폰), 유혹, 죄.", score: "N" }] },
            { q: "여행 계획을 짤 때 나는?", type: "SN", a: [{ text: "맛집 위치, 교통편, 숙소 가격 등 구체적인 정보를 찾는다.", score: "S" }, { text: "여행지의 분위기, 그곳에서 느낄 감정, 특별한 경험을 상상한다.", score: "N" }] },
            { q: "일을 처리하는 방식은?", type: "SN", a: [{ text: "검증된 방식, 매뉴얼, 선례를 따르는 것이 편하고 확실하다.", score: "S" }, { text: "남들이 안 해본 새로운 방식, 나만의 독창적인 방법을 시도하고 싶다.", score: "N" }] },
            { q: "추상적인 현대 미술 작품을 보았을 때?", type: "SN", a: [{ text: "음... 그냥 점이랑 선이네. 이게 뭐지?", score: "S" }, { text: "작가의 고뇌와 혼란스러운 내면이 느껴져.", score: "N" }] },
            { q: "설명서를 읽을 때 나는?", type: "SN", a: [{ text: "1번부터 순서대로 꼼꼼히 읽고 따라 한다.", score: "S" }, { text: "대충 그림만 훑어보고 일단 조립부터 해본다.", score: "N" }] },
            { q: "나에게 더 중요한 것은?", type: "SN", a: [{ text: "현재의 즐거움, 눈앞의 현실, 확실한 팩트.", score: "S" }, { text: "미래의 가능성, 보이지 않는 의미, 큰 그림.", score: "N" }] },
            { q: "후배가 실수를 해서 시말서를 써야 하는 상황이다. 나는?", type: "TF", a: [{ text: "규정은 규정이니 원칙대로 처리한다.", score: "T" }, { text: "사정을 들어보고 이번만 봐줄 수 있는지 알아본다.", score: "F" }] },
            { q: "리더로서 팀원을 평가해야 할 때?", type: "TF", a: [{ text: "성과와 능력 위주로 냉정하게 평가해야 공정하다.", score: "T" }, { text: "그 사람의 노력과 팀 분위기에 미친 영향도 중요하게 고려한다.", score: "F" }] },
            { q: "논쟁이 붙었을 때 나는?", type: "TF", a: [{ text: "내 논리가 맞다는 것을 증명하기 위해 끝까지 팩트를 제시한다.", score: "T" }, { text: "상대방의 기분이 상하지 않도록 적당히 맞춰주거나 화제를 돌린다.", score: "F" }] },
            { q: "나를 더 기분 좋게 하는 칭찬은?", type: "TF", a: [{ text: "너 진짜 똑똑하다. 일 처리 완벽해.", score: "T" }, { text: "너는 정말 따뜻한 사람이야. 배려심이 깊어.", score: "F" }] },
            { q: "의사결정을 내릴 때 더 신경 쓰이는 것은?", type: "TF", a: [{ text: "이것이 논리적으로 타당한가? 효율적인가?", score: "T" }, { text: "이것이 사람들에게 어떤 영향을 미칠까? 내 가치관에 맞는가?", score: "F" }] },
            { q: "친구가 늦어서 약속 시간에 늦었다. 친구는 '차가 너무 막혔어'라고 한다.", type: "TF", a: [{ text: "그러게 좀 일찍 나오지 그랬어.", score: "T" }, { text: "오느라 고생했네. 차 막히면 힘들지.", score: "F" }] },
            { q: "주말 일정이 갑자기 취소되었다면?", type: "JP", a: [{ text: "아... 계획 다 틀어졌네. 붕 뜬 시간에 당황하며 스트레스 받는다.", score: "J" }, { text: "오예! 자유시간이다! 즉흥적으로 하고 싶은 걸 하거나 쉰다.", score: "P" }] },
            { q: "내 방의 상태는?", type: "JP", a: [{ text: "물건들이 제자리에 정리되어 있고 깔끔하다.", score: "J" }, { text: "다소 어지럽혀져 있지만, 나름의 질서가 있어 찾을 순 있다.", score: "P" }] },
            { q: "새해 목표를 세울 때 나는?", type: "JP", a: [{ text: "3월까지 5kg 감량, 주 3회 운동 구체적인 수치와 계획을 짠다.", score: "J" }, { text: "올해는 더 건강해지기! 큰 방향성만 정해둔다.", score: "P" }] },
            { q: "반복되는 일상(루틴)에 대해 어떻게 생각하는가?", type: "JP", a: [{ text: "규칙적인 생활 패턴이 있어야 마음이 편하고 효율적이다.", score: "J" }, { text: "매일 똑같은 건 지루하다. 변화와 새로운 이벤트가 필요하다.", score: "P" }] },
            { q: "할 일 목록(To-Do List)을 작성하는가?", type: "JP", a: [{ text: "매일 작성하고 완료한 것을 체크하며 쾌감을 느낀다.", score: "J" }, { text: "머릿속으로 대충 생각하거나, 적어두고 까먹는 경우가 많다.", score: "P" }] },
            { q: "결정을 내려야 할 때 나는?", type: "JP", a: [{ text: "신속하게 결정을 내리고 다음 단계로 넘어가는 것을 선호한다.", score: "J" }, { text: "새로운 정보가 나올 수 있으므로 최대한 결정을 미루고 지켜본다.", score: "P" }] },
        ],
        results: {
            "ISTJ": { title: "소금쟁이", desc: "한 번 시작한 일은 끝까지 해내는 책임감 대장!", interpretation: "논리적이고 현실적인 당신은...", guide: "계획대로 흘러갈 때 편안함을 느낍니다.", mood: "cool", color: "bg-blue-100" },
            "ISFJ": { title: "수호천사", desc: "조용히 뒤에서 챙겨주는 배려의 아이콘", interpretation: "따뜻하고 헌신적인 당신은...", guide: "타인의 감정에 민감합니다.", mood: "happy", color: "bg-pink-100" },
            "INFJ": { title: "예언자", desc: "사람의 마음을 꿰뚫어 보는 통찰력", interpretation: "깊은 내면을 가진 당신은...", guide: "혼자만의 시간이 필요합니다.", mood: "sad", color: "bg-purple-100" },
            "INTJ": { title: "전략가", desc: "전체적인 판을 짜는 치밀한 계획가", interpretation: "독립적이고 분석적인 당신은...", guide: "지적 호기심이 강합니다.", mood: "cool", color: "bg-indigo-100" },
            "ISTP": { title: "장인", desc: "도구를 다루는 데 능숙한 만능 재주꾼", interpretation: "효율성을 중시하는 당신은...", guide: "자유로운 활동을 선호합니다.", mood: "cool", color: "bg-gray-100" },
            "ISFP": { title: "예술가", desc: "침대 밖은 위험해! 하지만 감성은 충만해", interpretation: "온화하고 겸손한 당신은...", guide: "자신의 가치관을 중요시합니다.", mood: "happy", color: "bg-yellow-100" },
            "INFP": { title: "몽상가", desc: "상상 속에서 세상을 구하는 로맨티스트", interpretation: "이상적인 세상을 꿈꾸는 당신은...", guide: "진정성을 추구합니다.", mood: "sad", color: "bg-green-100" },
            "INTP": { title: "아이디어뱅크", desc: "멍 때리는 것 같지만 머릿속은 우주 여행 중", interpretation: "논리적이고 비판적인 당신은...", guide: "지적 탐구를 즐깁니다.", mood: "cool", color: "bg-blue-100" },
            "ESTP": { title: "모험가", desc: "인생은 실전! 스릴을 즐기는 승부사", interpretation: "에너지 넘치는 당신은...", guide: "즉흥적인 활동을 좋아합니다.", mood: "excited", color: "bg-red-100" },
            "ESFP": { title: "연예인", desc: "내가 가는 곳이 곧 무대! 분위기 메이커", interpretation: "사교적이고 활동적인 당신은...", guide: "사람들과 어울리는 것을 좋아합니다.", mood: "happy", color: "bg-orange-100" },
            "ENFP": { title: "스파크", desc: "열정이 팡팡! 사람을 좋아하는 댕댕이 재질", interpretation: "창의적이고 열정적인 당신은...", guide: "새로운 가능성을 찾습니다.", mood: "excited", color: "bg-yellow-100" },
            "ENTP": { title: "발명가", desc: "이건 왜 안 돼? 끊임없이 질문하는 토론왕", interpretation: "독창적이고 다재다능한 당신은...", guide: "지적인 도전을 즐깁니다.", mood: "cool", color: "bg-red-100" },
            "ESTJ": { title: "감독관", desc: "약속 시간 늦는 건 절대 용납 못 해!", interpretation: "체계적이고 규칙적인 당신은...", guide: "책임감이 강합니다.", mood: "cool", color: "bg-blue-200" },
            "ESFJ": { title: "친선도모", desc: "리액션 부자! 친구들의 고민 상담사", interpretation: "친절하고 사교적인 당신은...", guide: "조화를 중요시합니다.", mood: "happy", color: "bg-pink-200" },
            "ENFJ": { title: "언변가", desc: "사람들을 이끄는 따뜻한 카리스마", interpretation: "타인의 성장을 돕는 당신은...", guide: "공감 능력이 뛰어납니다.", mood: "happy", color: "bg-purple-200" },
            "ENTJ": { title: "지도자", desc: "목표를 향해 돌진하는 불도저 리더", interpretation: "결단력 있고 통솔력 있는 당신은...", guide: "비전을 제시합니다.", mood: "cool", color: "bg-indigo-200" }
        }
    },
    cat: {
        title: "고양이 성격 테스트",
        themeColor: "bg-[#FFD1DC]",
        icon: "CatFace",
        questions: [
            { q: "집사가 화장실에 들어갔다. 문이 닫히면?", type: "EI", a: [{ text: "문 앞에서 야옹거리거나 앞발을 넣는다.", score: "E" }, { text: "나올 때까지 조용히 기다리거나 내 할 일 한다.", score: "I" }] },
            { q: "집에 낯선 손님이 찾아왔을 때?", type: "EI", a: [{ text: "누구냐옹? 먼저 다가가서 냄새를 맡는다.", score: "E" }, { text: "후다닥! 침대 밑이나 높은 곳으로 숨는다.", score: "I" }] },
            { q: "집사가 장난감을 흔들 때?", type: "EI", a: [{ text: "우다다다! 바로 달려들어 사냥한다.", score: "E" }, { text: "누워서 발만 까딱까딱... 귀찮다옹.", score: "I" }] },
            { q: "창밖을 구경할 때 나는?", type: "SN", a: [{ text: "지나가는 새, 벌레를 보며 채터링(깍깍)을 한다.", score: "S" }, { text: "그냥 멍하니 풍경을 바라보며 사색에 잠긴다.", score: "N" }] },
            { q: "새로운 박스가 생겼다!", type: "SN", a: [{ text: "일단 들어가서 사이즈가 맞는지 확인한다.", score: "S" }, { text: "이건 우주선이다옹! 상상하며 뜯고 맛본다.", score: "N" }] },
            { q: "사냥 놀이를 할 때?", type: "SN", a: [{ text: "눈앞에 보이는 장난감만 쫓는다.", score: "S" }, { text: "장난감이 숨을 곳을 미리 예측하고 매복한다.", score: "N" }] },
            { q: "집사가 슬퍼서 울고 있을 때?", type: "TF", a: [{ text: "배고프다옹. 밥그릇을 툭툭 친다.", score: "T" }, { text: "왜 그러냐옹... 조용히 다가와서 눈물을 핥아준다.", score: "F" }] },
            { q: "집사에게 혼났을 때?", type: "TF", a: [{ text: "흥! 꼬리를 홱 돌리고 무시한다.", score: "T" }, { text: "마징가 귀를 하고 눈치를 본다.", score: "F" }] },
            { q: "간식을 줄 때 집사의 손가락까지 깨물었다!", type: "TF", a: [{ text: "맛있는 냄새가 나서 그랬다옹. (당당)", score: "T" }, { text: "아팠냐옹? 미안해서 핥아준다.", score: "F" }] },
            { q: "밥 먹을 시간이 되었을 때?", type: "JP", a: [{ text: "정확한 시간에 야옹! 밥 내놔라옹!", score: "J" }, { text: "자다가 생각나면 가서 먹는다.", score: "P" }] },
            { q: "화장실을 사용할 때?", type: "JP", a: [{ text: "모래를 꼼꼼하게 덮어서 흔적을 없앤다.", score: "J" }, { text: "대충 덮거나 그냥 튀어 나간다.", score: "P" }] },
            { q: "잠자는 위치는?", type: "JP", a: [{ text: "항상 자는 지정석(캣타워, 집사 베개 등)이 있다.", score: "J" }, { text: "그때그때 기분 내키는 곳에서 잔다.", score: "P" }] },
        ],
        questions_deep: [
            { q: "다른 고양이 친구를 만났을 때?", type: "EI", a: [{ text: "반갑다옹! 코 인사를 시도한다.", score: "E" }, { text: "하악! 가까이 오지 마라옹!", score: "I" }] },
            { q: "집사가 이름을 불렀을 때?", type: "EI", a: [{ text: "야옹~ 하고 대답하며 달려간다.", score: "E" }, { text: "귀만 쫑긋하고 못 들은 척한다.", score: "I" }] },
            { q: "집안에서 나의 활동 반경은?", type: "EI", a: [{ text: "거실, 부엌, 안방... 온 집안을 누비고 다닌다.", score: "E" }, { text: "내 구역(캣타워, 숨숨집)에서 잘 안 나온다.", score: "I" }] },
            { q: "새로운 장난감을 사왔을 때?", type: "EI", a: [{ text: "신상이다! 바로 관심을 보이며 가지고 논다.", score: "E" }, { text: "며칠 동안 냄새만 맡으며 탐색전을 벌인다.", score: "I" }] },
            { q: "집사가 외출하고 돌아왔을 때?", type: "EI", a: [{ text: "현관까지 마중 나가서 다리에 몸을 비빈다.", score: "E" }, { text: "왔어? 자다가 눈만 한번 뜬다.", score: "I" }] },
            { q: "밤에 모두가 잠든 시간, 나는?", type: "EI", a: [{ text: "우다다 타임! 혼자서도 잘 논다.", score: "E" }, { text: "집사 옆에 붙어서 같이 잔다.", score: "I" }] },
            { q: "높은 곳(냉장고 위, 장롱 위)을 볼 때?", type: "SN", a: [{ text: "올라갈 수 있을까? 각도를 계산해본다.", score: "S" }, { text: "저기는 정복해야 할 나의 성이다옹!", score: "N" }] },
            { q: "거울을 볼 때?", type: "SN", a: [{ text: "그냥 나네. (무관심)", score: "S" }, { text: "저 녀석은 누구냐옹? 뒤에 누가 있나 확인한다.", score: "N" }] },
            { q: "벌레가 나타났다!", type: "SN", a: [{ text: "잡았다! 바로 앞발로 내리친다.", score: "S" }, { text: "저건 뭘까? 뚫어져라 관찰하며 채터링한다.", score: "N" }] },
            { q: "집사가 이상한 자세로 있을 때?", type: "SN", a: [{ text: "뭐하냐옹? 냄새를 맡아본다.", score: "S" }, { text: "새로운 놀이인가? 같이 이상한 자세를 취한다.", score: "N" }] },
            { q: "간식 서랍을 열지도 않았는데 달려간다?", type: "SN", a: [{ text: "봉지 부스럭거리는 소리를 들었다.", score: "S" }, { text: "집사의 기운이 간식을 줄 것 같았다.", score: "N" }] },
            { q: "TV에 새가 나올 때?", type: "SN", a: [{ text: "저건 가짜다옹. 별 반응 없다.", score: "S" }, { text: "잡고 싶다옹! TV 화면을 긁는다.", score: "N" }] },
            { q: "집사가 아파서 누워있을 때?", type: "TF", a: [{ text: "심심하다옹. 놀아달라고 깨운다.", score: "T" }, { text: "걱정된다옹. 옆에서 골골송으로 치유해준다.", score: "F" }] },
            { q: "발톱 깎을 때?", type: "TF", a: [{ text: "이거 놓으라옹! (하악질/냥펀치)", score: "T" }, { text: "싫지만 츄르를 위해 참는다. (낑낑)", score: "F" }] },
            { q: "집사가 실수로 꼬리를 밟았다!", type: "TF", a: [{ text: "캬악! (바로 응징)", score: "T" }, { text: "야옹! (아프지만 도망가서 쳐다봄)", score: "F" }] },
            { q: "맛없는 간식을 줬을 때?", type: "TF", a: [{ text: "냄새 맡고 홱 돌아서 가버린다.", score: "T" }, { text: "일단 먹는 시늉은 해준다.", score: "F" }] },
            { q: "집사가 뽀뽀하려고 다가올 때?", type: "TF", a: [{ text: "앞발로 입을 막는다. (거절)", score: "T" }, { text: "눈을 감고 받아준다. (허락)", score: "F" }] },
            { q: "원하는 것을 요구할 때?", type: "TF", a: [{ text: "물건을 떨어뜨리거나 긁어서 관심을 끈다.", score: "T" }, { text: "애처로운 눈빛으로 야옹~ 하고 운다.", score: "F" }] },
            { q: "스크래쳐 사용 방식은?", type: "JP", a: [{ text: "항상 긁던 곳만 긁어서 너덜너덜하다.", score: "J" }, { text: "소파, 벽지, 카펫... 긁히는 건 다 긁는다.", score: "P" }] },
            { q: "그루밍(털 고르기) 스타일은?", type: "JP", a: [{ text: "발가락 사이까지 꼼꼼하게 순서대로 한다.", score: "J" }, { text: "생각날 때마다 대충 핥는다.", score: "P" }] },
            { q: "집안 가구 배치가 바뀌었을 때?", type: "JP", a: [{ text: "마음에 안 든다옹! 계속 울거나 불안해한다.", score: "J" }, { text: "오! 새로운 탐험지다옹! 신나게 돌아다닌다.", score: "P" }] },
            { q: "사료 먹는 스타일?", type: "JP", a: [{ text: "딱 먹을 만큼만 먹고 남긴다. (자율급식 가능)", score: "J" }, { text: "있으면 다 먹어치운다. (식탐왕)", score: "P" }] },
            { q: "집사가 놀아주는 시간?", type: "JP", a: [{ text: "매일 밤 10시! 루틴이 깨지면 화낸다.", score: "J" }, { text: "집사가 낚싯대 들면 그때가 노는 시간이다.", score: "P" }] },
            { q: "낯선 물건에 대한 반응?", type: "JP", a: [{ text: "조심스럽게 냄새 맡고 안전한지 확인 후 건드린다.", score: "J" }, { text: "일단 앞발로 툭 쳐보고 올라가 본다.", score: "P" }] },
        ],
        results: results_cat
    },
    dog: {
        title: "강아지 성격 테스트",
        themeColor: "bg-[#FFC95F]",
        icon: "DogFace",
        questions: [
            { q: "산책 중 다른 강아지를 만났을 때?", type: "EI", a: [{ text: "안녕! 꼬리 흔들며 격하게 인사한다.", score: "E" }, { text: "보호자 뒤로 숨거나 못 본 척 지나간다.", score: "I" }] },
            { q: "애견 카페에 갔을 때?", type: "EI", a: [{ text: "우다다! 친구들과 어울려 뛰어논다.", score: "E" }, { text: "내 무릎 위나 의자 밑에만 있는다.", score: "I" }] },
            { q: "집에 손님이 왔을 때?", type: "EI", a: [{ text: "누구세요! 짖으면서도 꼬리는 흔든다.", score: "E" }, { text: "방에 들어가서 나올 생각을 안 한다.", score: "I" }] },
            { q: "산책할 때 나는?", type: "SN", a: [{ text: "땅바닥 냄새 맡느라 앞으로 못 간다.", score: "S" }, { text: "나비나 새를 쫓아다니느라 정신없다.", score: "N" }] },
            { q: "간식을 숨겨놨을 때?", type: "SN", a: [{ text: "킁킁! 냄새를 따라 정확히 찾아낸다.", score: "S" }, { text: "어디 있지? 엉뚱한 곳을 파거나 짖는다.", score: "N" }] },
            { q: "보호자가 옷을 입을 때?", type: "SN", a: [{ text: "산책 가는 옷인지 출근복인지 귀신같이 안다.", score: "S" }, { text: "옷만 입으면 무조건 나가는 줄 알고 신난다.", score: "N" }] },
            { q: "혼났을 때 반응은?", type: "TF", a: [{ text: "뭐가 문젠데? 억울하다는 듯 쳐다본다.", score: "T" }, { text: "잘못했어요... 배를 보이며 납작 엎드린다.", score: "F" }] },
            { q: "보호자가 울고 있을 때?", type: "TF", a: [{ text: "옆에 가만히 앉아서 지켜본다.", score: "T" }, { text: "얼굴을 핥고 안절부절못한다.", score: "F" }] },
            { q: "다른 강아지가 으르렁거릴 때?", type: "TF", a: [{ text: "같이 으르렁! 지지 않는다.", score: "T" }, { text: "깨갱... 꼬리를 내리고 피한다.", score: "F" }] },
            { q: "산책 코스는?", type: "JP", a: [{ text: "항상 가던 길로 가야 마음이 편하다.", score: "J" }, { text: "오늘은 저쪽이다! 발길 닿는 대로 간다.", score: "P" }] },
            { q: "배변 습관은?", type: "JP", a: [{ text: "배변 패드 정중앙에 정확히 싼다.", score: "J" }, { text: "가끔 모서리에 싸거나 실수를 한다.", score: "P" }] },
            { q: "기다려 훈련을 할 때?", type: "JP", a: [{ text: "먹으라고 할 때까지 침 흘리며 참는다.", score: "J" }, { text: "못 참아! 눈치 보며 슬금슬금 먹는다.", score: "P" }] },
        ],
        questions_deep: [
            { q: "엘리베이터에서 이웃을 만났을 때?", type: "EI", a: [{ text: "반갑다고 꼬리 치며 다가가려 한다.", score: "E" }, { text: "구석에 얌전히 앉아 있는다.", score: "I" }] },
            { q: "놀아달라고 할 때?", type: "EI", a: [{ text: "장난감을 물고 와서 무릎에 툭 던진다.", score: "E" }, { text: "그윽한 눈빛으로 쳐다보며 텔레파시를 보낸다.", score: "I" }] },
            { q: "TV에서 동물 소리가 날 때?", type: "EI", a: [{ text: "같이 짖거나 TV 앞으로 달려간다.", score: "E" }, { text: "별 관심 없이 잠만 잔다.", score: "I" }] },
            { q: "가족들이 다 모여 있을 때?", type: "EI", a: [{ text: "그 한가운데 자리를 잡고 눕는다.", score: "E" }, { text: "조용한 방이나 자기 집으로 들어간다.", score: "I" }] },
            { q: "처음 보는 강아지에게?", type: "EI", a: [{ text: "놀자! 엉덩이를 들고 플레이 바우를 한다.", score: "E" }, { text: "냄새만 살짝 맡고 내 갈 길 간다.", score: "I" }] },
            { q: "미용실에 갔을 때?", type: "EI", a: [{ text: "미용사 선생님이랑 노느라 바쁘다.", score: "E" }, { text: "잔뜩 긴장해서 얼음이 된다.", score: "I" }] },
            { q: "거울 속의 자신을 볼 때?", type: "SN", a: [{ text: "그냥 나네. (냄새가 안 나니까 무시)", score: "S" }, { text: "누구냐 넌! 짖거나 뒤를 찾아본다.", score: "N" }] },
            { q: "산책 중 낙엽이 굴러갈 때?", type: "SN", a: [{ text: "바스락 소리에 귀를 쫑긋한다.", score: "S" }, { text: "살아있는 생물인 줄 알고 사냥하려 든다.", score: "N" }] },
            { q: "보호자의 표정 변화를?", type: "SN", a: [{ text: "목소리 톤이나 행동으로 기분을 파악한다.", score: "S" }, { text: "눈빛만 봐도 기분을 귀신같이 알아챈다.", score: "N" }] },
            { q: "장난감을 고를 때?", type: "SN", a: [{ text: "익숙한 공이나 인형을 선호한다.", score: "S" }, { text: "소리가 나거나 움직이는 신기한 걸 좋아한다.", score: "N" }] },
            { q: "간식 줄까? 말만 했을 때?", type: "SN", a: [{ text: "진짜 줄 때까지 기다린다.", score: "S" }, { text: "이미 침 흘리며 앉아 있다.", score: "N" }] },
            { q: "자다가 꿈을 꿀 때?", type: "SN", a: [{ text: "가끔 움찔거리는 정도다.", score: "S" }, { text: "달리기하고 짖고 난리가 난다.", score: "N" }] },
            { q: "간식을 공평하게 나눠주지 않았을 때?", type: "TF", a: [{ text: "내 밥그릇을 지키려고 으르렁댄다.", score: "T" }, { text: "시무룩해져서 구석으로 간다.", score: "F" }] },
            { q: "발을 밟혔을 때?", type: "TF", a: [{ text: "깨갱! 하고 자리를 피한다.", score: "T" }, { text: "아파 ㅠㅠ 안아달라고 매달린다.", score: "F" }] },
            { q: "목욕하기 싫을 때?", type: "TF", a: [{ text: "버티기! 힘으로 저항한다.", score: "T" }, { text: "불쌍한 표정으로 호소한다.", score: "F" }] },
            { q: "칭찬받았을 때?", type: "TF", a: [{ text: "당당하게 간식을 요구한다.", score: "T" }, { text: "온몸으로 기쁨을 표현하며 날뛴다.", score: "F" }] },
            { q: "보호자가 아픈 척 쓰러지면?", type: "TF", a: [{ text: "뭐해? 툭툭 건드려 본다.", score: "T" }, { text: "큰일 났다! 핥고 짖고 난리 난다.", score: "F" }] },
            { q: "서열 정리가 필요할 때?", type: "TF", a: [{ text: "내가 이 구역의 짱이다. 기싸움한다.", score: "T" }, { text: "평화가 좋아. 바로 배를 보인다.", score: "F" }] },
            { q: "산책 시간 알림?", type: "JP", a: [{ text: "시간 되면 줄을 물고 온다.", score: "J" }, { text: "나가자고 할 때까지 기다린다.", score: "P" }] },
            { q: "잠자리 위치?", type: "JP", a: [{ text: "내 방석, 내 집. 정해진 곳에서만 잔다.", score: "J" }, { text: "소파, 침대, 바닥... 시원한 곳 찾아다닌다.", score: "P" }] },
            { q: "밥 먹는 속도?", type: "JP", a: [{ text: "꼭꼭 씹어서 일정하게 먹는다.", score: "J" }, { text: "숨도 안 쉬고 흡입한다.", score: "P" }] },
            { q: "새로운 개인기를 배울 때?", type: "JP", a: [{ text: "반복하면 금방 배운다.", score: "J" }, { text: "집중력이 짧아서 금방 딴짓한다.", score: "P" }] },
            { q: "산책 중 갈림길에서?", type: "JP", a: [{ text: "보호자가 이끄는 대로 잘 따라간다.", score: "J" }, { text: "내가 가고 싶은 길로 가려고 고집 부린다.", score: "P" }] },
            { q: "장난감 정리?", type: "JP", a: [{ text: "자기 집에 물어다 놓는다. (천재견?)", score: "J" }, { text: "온 집안에 흩뿌려 놓는다.", score: "P" }] },
        ],
        results: results_dog
    }
};

window.MBTI_DATA = { results_cat, results_dog, appData };
